### ISSUE TITLE
Add 4 placeholder pages for Analytics and update navigation and routing

### ISSUE THREAD

**Issue by JuniorDieka** [unisdr/DELTA#11]
### Description
Using the Figma https://www.figma.com/design/noegprarmNGSsk4BQlMVtY/DLDTS-Design-System-and-Screens?node-id=18-2736&t=QQ9JmbGyswGbXUom-4  

### Tasks
**✓** Create 4 placeholder pages (Human Direct Effects, Sectors, Hazards and Disaster Events) with appropriate routes and WIP messages.
**✓** Update navigation in header.tsx to reflect the new routes.
**✓** Refactor nav.tsx and route.tsx for dynamic sub-navigation.

### Acceptance Criteria
- [ ] Placeholder pages are accessible at their respective routes.
- [ ] Navigation highlights the correct page in the sub-menu.
- [ ] Navigation dynamically updates based on the active section (Settings or Analytics).
- [ ] Analytics must be available to public is database is set to public otherwise requires password if database is set to private.
