### ISSUE TITLE
Enhanced Login Page UI and Error Handling

### ISSUE THREAD

**Issue by JuniorDieka** [unisdr/DELTA#16]
### Description
I've updated the login page to improve user experience and error handling. 

### Tasks
- [ ]  Enhanced visual design with clear instructions and required information.
- [ ] Improved form error displays, showing error as per the figma https://www.figma.com/design/noegprarmNGSsk4BQlMVtY/DLDTS-Design-System-and-Screens?node-id=1195-53949&t=l7piGueG4l7OkCIJ-4.
- [ ] Added functionality to toggle password visibility.
