### ISSUE TITLE
Enhance Access Management Page with Filters, User Stats, and Responsive Layout

### ISSUE THREAD

**Issue by JuniorDieka** [unisdr/DELTA#18]
### Description
I have updated to improve usability and aesthetics on the Access Management index page as per the https://www.figma.com/design/noegprarmNGSsk4BQlMVtY/DLDTS-Design-System-and-Screens?node-id=159-14865&t=5HsYPCXXQ5yq8xqH-4.

### Tasks
- [ ] Added a filter form.
- [ ] Introduced User Stats.
- [ ] Enhanced Role Column.
- [ ] Improved Buttons.
